from cycler import Cycler
import time

c = Cycler()
print("Serial open: {0}".format(c.portOpen))
c.run_program('"PFUNKEL1"')
print(c.get_run()[0])
print(c.get_run('stepNum'))
print(c.send('PROCEED\r\n'))
print(c.get_run('stepNum'))
print(c.send('PROCEED\r\n'))
print(c.get_run('stepNum'))
print('Busy? {0}'.format(c.check_busy()))
#print(c.get_run('vesselType'))
#print(c.get_run('vesselVol'))
#c.set_calc()
#print(c.get_run('vesselType'))
#print(c.get_run('vesselVol'))
#resp=c.run_program('"TEST"')
#print(c.get_run('targetTemp'))
#print(c.get_run('blockTemp'))
#c.incubate(10,True)
#print(c.get_run('targetTemp'))
#print(c.get_run('blockTemp'))
#c.cancel()
#print(c.get_run())
#print(c.get_run('vesselType'))
#print(c.get_run('vesselVol'))
#for key,val in c._runQ.items():
#    print(key)
#    print(c.get_run(key))
#print("Canceling Run")
#c.cancel()
#while True:
#    resp = c.get_run()
#    print(resp)
#    if resp[0] == '""':
#        print("Run Ended")
#        break 
#    c.cancel()
#    time.sleep(1) 
#
#print(c.lidOpen)
#c.toggle_lid()
#print(c.send(c._lid['status'])) 
#print(c.lidOpen)
